#!/bin/bash

function MergeOneRun()
{
	local dir="$1"

	cd "$dir" || return

	rm -f "merged.root"

	input=""
	for idxDir in idx*
	do
		if [ -s "$idxDir/success" -a -s "$idxDir/output.root" ]
		then
			input="$input $idxDir/output.root"
		fi
	done

	if [ "$input" != "" ]
	then
		echo "* $dir: merging started"
		hadd "merged.root" $input &> "merged.log" || exit
		echo "* $dir: merging done"
	fi

	cd - > /dev/null
}

#----------------------------------------------------------------------------------------------------

function MergeOneDataSet()
{
	local dir="$1"

	cd "$dir" || return

	echo "* $dir"

	rm -f "merged.root"
	hadd "merged.root" */merged.root || exit

	cd - > /dev/null
}

#----------------------------------------------------------------------------------------------------

MergeOneRun "TOTEM2/319176" &
MergeOneRun "TOTEM2/319256" &
MergeOneRun "TOTEM2/319262" &
MergeOneRun "TOTEM2/319263" &

wait

MergeOneRun "TOTEM2/319265" &
MergeOneRun "TOTEM2/319268" &
MergeOneRun "TOTEM2/319300" &
MergeOneRun "TOTEM2/319311" &

wait
MergeOneDataSet "TOTEM2"

#-----

MergeOneRun "TOTEM4/319176" &
MergeOneRun "TOTEM4/319256" &
MergeOneRun "TOTEM4/319262" &
MergeOneRun "TOTEM4/319263" &

wait

MergeOneRun "TOTEM4/319265" &
MergeOneRun "TOTEM4/319268" &
MergeOneRun "TOTEM4/319300" &
MergeOneRun "TOTEM4/319311" &

wait
MergeOneDataSet "TOTEM4"
