#!/bin/bash

#----------------------------------------------------------------------------------------------------

function PrintUsage()
{
	echo "USAGE: submit [job name] [input file] [output dir] [file per block]"
}

#----------------------------------------------------------------------------------------------------

function MakeJob()
{
	job_file="$dir/job"

	cat "job_template" | sed "\
			s|\$WORK_DIR|$cwd/$dir|;\
			s|\$CMSSW_BASE|$CMSSW_BASE|;\
		" > "$job_file"

	chmod u+x "$job_file"
}

#----------------------------------------------------------------------------------------------------

function MakeCfg()
{
	cfg_file="$dir/cfg.py"

	cat "template_cfg.py" | sed "\
			s|\$INPUT|$buffer|;\
		" > "$cfg_file"
}

#----------------------------------------------------------------------------------------------------

job_name="$1"
input_file="$2"
output_dir="$3"
files_per_block="$4"

cwd=`pwd -P`

if [ -z "$job_name" -o ! -f "$input_file" -o -z "$output_dir" -o -z "$files_per_block" ]
then
	PrintUsage
	exit 1
fi

mkdir -p "$output_dir"

sub_script="$output_dir/condor.sub"

base_dir="$cwd/$output_dir"

#----------------------------------------------------------------------------------------------------

function FlushBlock()
{
	idxDir="idx$block_idx"
	dir="$output_dir/$idxDir"
	echo "* $dir"

	# make and clean directory
	mkdir -p "$dir"

	rm -f "$dir/submitted"
	rm -f "$dir/finished"
	rm -f "$dir/success"

	rm -f "$dir/out"
	rm -f "$dir/err"
	rm -f "$dir/log"
	rm -f "$dir/output.root"

	MakeJob

	MakeCfg

	(
		echo ""
		echo "dir=$idxDir"
		echo "queue"
	) >> "$sub_script"

	buffer=""
	buffer_size=0
	let block_idx=$block_idx+1
}

#----------------------------------------------------------------------------------------------------

(
	echo "executable = $base_dir/\$(dir)/job"
	echo "arguments = \$(ClusterId) \$(ProcId) \\\"\$(dir)\\\""
	echo "output = $base_dir/\$(dir)/out"
	echo "error = $base_dir/\$(dir)/err"
	echo "log = $base_dir/condor.log"

	#echo "+JobFlavour = \"espresso\"" # 20 minutes
	#echo "+JobFlavour = \"microcentury\"" # 1 hour
	echo "+MaxRuntime = 7200" # in s

	echo "+JobBatchName = \"$output_dir\""

	echo "requirements = (OpSysAndVer =?= \"SLCern6\")"

) > "$sub_script"

buffer=""
buffer_size=0
block_idx=0

for row in `cat $input_file`
do
	buffer="$buffer $row"
	let buffer_size+=1

	if [ "$buffer_size" -ge "$files_per_block" ]
	then
		FlushBlock
	fi
done

if [ "$buffer_size" -gt "0" ]
then
	FlushBlock
fi

echo "Submitting ..."
condor_submit "$sub_script"
