#!/bin/bash

#input_dir="input/AOD"
input_dir="input/reduced"

output_dir="output_vtxZ_eta_px130_pixReq_noExtAct"

streams=(
	"TOTEM2"
	"TOTEM4"
)

runs=(
	"319176"
	"319256"
	"319262"
	"319263"
	"319265"
	"319268"
	"319300"
	"319311"
)

files_per_block="15"

for stream in ${streams[*]}
do
	for run in ${runs[*]}
	do
		echo "$stream $run"
		./submit "$stream/$run" "$input_dir/${stream}_${run}" "$output_dir/${stream}/${run}" "$files_per_block"
	done
done
